"""
TraceNet Backend - Mock Data Module
All data here mirrors the existing React frontend mock data exactly.
"""

# ─── Slides (from data.js) ───────────────────────────────────────────────────

slides = [
    {
        "title": "Trace Net Intelligence Core",
        "desc": "Modern cities operate on isolated camera feeds. Trace Net integrates cross-sector infrastructure using centralized computer vision and deep learning to deliver real-time traffic visibility, trajectory reconstruction, and congestion analytics.",
    },
    {
        "title": "High-Accuracy ANPR & OCR Engine",
        "desc": "Optical Recognition Core: Advanced deep learning architecture achieving >96.8% precision across harsh environmental conditions, high-speed motion blur, angled multi-lane shots, and faded or damaged license plates.",
    },
    {
        "title": "Macro Traffic Flow & Origin Analytics",
        "desc": "City Dynamics: Aggregates over 250+ live feeds to continuously map corridor density, compute origin-destination matrices, forecast bottlenecks 30 minutes in advance, and optimize traffic signal timing dynamically.",
    },
    {
        "title": "Autonomous Threat & Incident Response",
        "desc": "Security Layer: Instantly flags blacklisted vehicles, anomalous loitering patterns, and erratic lane-changing behaviors with automated dispatch alerts routed directly to local command posts.",
    },
]

# ─── Areas (from data.js) ────────────────────────────────────────────────────

areas = [
    {
        "name": "Kukatpally",
        "title": "Kukatpally Zone",
        "sector": "Sector NW-1",
        "density": "High (Congestion Detected)",
        "speed": "36 km/h",
        "cameras": "54 ANPR Cameras",
        "accuracy": "95.1%",
        "status": "Critical Load",
        "peakHours": "17:30 - 20:00",
        "incidents": 4,
        "color": "#ff3b30",
        "position": [17.4932, 78.3984],
    },
    {
        "name": "Balanagar",
        "title": "Balanagar Corridor",
        "sector": "Sector N-2",
        "density": "Moderate",
        "speed": "48 km/h",
        "cameras": "38 ANPR Cameras",
        "accuracy": "93.7%",
        "status": "Stable Flow",
        "peakHours": "08:30 - 10:30",
        "incidents": 1,
        "color": "#ffcc00",
        "position": [17.5180, 78.4275],
    },
    {
        "name": "Cyberabad / Madhapur",
        "title": "Cyberabad Hub (Madhapur)",
        "sector": "Sector W-4",
        "density": "Very High Flow",
        "speed": "42 km/h",
        "cameras": "72 ANPR Cameras",
        "accuracy": "96.4%",
        "status": "Heavy Commuter Surge",
        "peakHours": "16:00 - 21:00",
        "incidents": 7,
        "color": "#007aff",
        "position": [17.4483, 78.3915],
    },
    {
        "name": "Begumpet",
        "title": "Begumpet Central",
        "sector": "Sector C-1",
        "density": "Moderate Density",
        "speed": "40 km/h",
        "cameras": "41 ANPR Cameras",
        "accuracy": "94.2%",
        "status": "Normal Operations",
        "peakHours": "09:00 - 11:00",
        "incidents": 2,
        "color": "#ffcc00",
        "position": [17.4440, 78.4670],
    },
    {
        "name": "Secunderabad",
        "title": "Secunderabad Hub",
        "sector": "Sector E-3",
        "density": "Normal Flow",
        "speed": "55 km/h",
        "cameras": "49 ANPR Cameras",
        "accuracy": "92.8%",
        "status": "Optimal Flow",
        "peakHours": "08:00 - 10:00",
        "incidents": 0,
        "color": "#34c759",
        "position": [17.4399, 78.4983],
    },
]

# ─── Cameras (from data.js) ──────────────────────────────────────────────────

cameras = [
    {
        "id": "CAM #401",
        "location": "Kukatpally Flyover Junction",
        "latitude": 17.4932,
        "longitude": 78.3984,
        "speed": "34 km/h",
        "density": "High (84%)",
        "trend": "Traffic ↑ 18% since 4:00 PM",
        "status": "Online",
        "resolution": "4K AI Optical Stream",
        "fps": 60,
        "color": "#e64638",
        "flow": [0.4, 0.7, 1.0, 0.8, 0.5, 0.9],
        "vehicleClasses": {"cars": "62%", "bikes": "24%", "trucks": "14%"},
        "lastPlateRead": "TS08EJ4892",
    },
    {
        "id": "CAM #402",
        "location": "Kukatpally Metro Station Gate 2",
        "latitude": 17.4891,
        "longitude": 78.4012,
        "speed": "28 km/h",
        "density": "Very High (92%)",
        "trend": "Traffic ↑ 24% since 3:30 PM",
        "status": "Online",
        "resolution": "1080p IR Night-Enhanced",
        "fps": 30,
        "color": "#e64638",
        "flow": [0.5, 0.9, 1.15, 0.85, 0.6, 1.1],
        "vehicleClasses": {"cars": "55%", "bikes": "35%", "trucks": "10%"},
        "lastPlateRead": "TS07FZ1029",
    },
    {
        "id": "CAM #403",
        "location": "Balanagar Main Road Circle",
        "latitude": 17.4855,
        "longitude": 78.4120,
        "speed": "48 km/h",
        "density": "Medium (56%)",
        "trend": "Traffic ↑ 4% since 4:00 PM",
        "status": "Online",
        "resolution": "4K Wide Angle Matrix",
        "fps": 60,
        "color": "#f4be25",
        "flow": [0.3, 0.5, 0.7, 0.6, 0.4, 0.5],
        "vehicleClasses": {"cars": "48%", "bikes": "30%", "trucks": "22%"},
        "lastPlateRead": "TS10UA9921",
    },
    {
        "id": "CAM #404",
        "location": "Moosapet Bypass Link",
        "latitude": 17.4810,
        "longitude": 78.4055,
        "speed": "56 km/h",
        "density": "Low (32%)",
        "trend": "Traffic ↓ 6% since 4:00 PM",
        "status": "Online",
        "resolution": "1080p Standard Telephoto",
        "fps": 30,
        "color": "#52b788",
        "flow": [0.2, 0.4, 0.5, 0.3, 0.3, 0.25],
        "vehicleClasses": {"cars": "70%", "bikes": "20%", "trucks": "10%"},
        "lastPlateRead": "TS15EX5540",
    },
]

# ─── System Metrics (from data.js) ───────────────────────────────────────────

system_metrics = {
    "totalNodesActive": 254,
    "networkUptime": "99.98%",
    "averageInferenceLatency": "14ms",
    "platesIndexedToday": "1,428,910",
    "activeAlertsCount": 3,
}

# ─── Dashboard Camera Data (from DashboardPage.jsx) ─────────────────────────

dashboard_cameras = [
    {
        "id": "CAM-01 (Kukatpally Y-Junction)",
        "lat": 17.4947,
        "lng": 78.3996,
        "status": "High",
        "speed": "12",
        "densityValue": 94,
        "density": "94%",
        "trend": "Severe Gridlock",
        "trafficChange": "+45%",
        "since": "4 PM",
        "color": "#ef4444",
    },
    {
        "id": "CAM-02 (JNTU Main Road)",
        "lat": 17.4985,
        "lng": 78.3912,
        "status": "Med",
        "speed": "35",
        "densityValue": 65,
        "density": "65%",
        "trend": "Moderate Flow",
        "trafficChange": "+15%",
        "since": "5 PM",
        "color": "#f97316",
    },
    {
        "id": "CAM-03 (KPHB Colony Phase 1)",
        "lat": 17.4855,
        "lng": 78.3895,
        "status": "Low",
        "speed": "55",
        "densityValue": 25,
        "density": "25%",
        "trend": "Clear Route",
        "trafficChange": "-10%",
        "since": "3 PM",
        "color": "#10b981",
    },
    {
        "id": "CAM-04 (Balanagar Cross)",
        "lat": 17.4682,
        "lng": 78.4357,
        "status": "High",
        "speed": "18",
        "densityValue": 88,
        "density": "88%",
        "trend": "Heavy Congestion",
        "trafficChange": "+30%",
        "since": "4 PM",
        "color": "#ef4444",
    },
]

dashboard_flow_trends = [
    {"time": "6 AM", "volume": 4000},
    {"time": "9 AM", "volume": 11000},
    {"time": "12 PM", "volume": 7500},
    {"time": "3 PM", "volume": 8500},
    {"time": "6 PM", "volume": 13500},
    {"time": "9 PM", "volume": 5000},
]

dashboard_density_trends = [
    {"time": "6 AM", "density": 25},
    {"time": "9 AM", "density": 92},
    {"time": "12 PM", "density": 55},
    {"time": "3 PM", "density": 70},
    {"time": "6 PM", "density": 95},
    {"time": "9 PM", "density": 35},
]

dashboard_congestion_trends = [
    {"time": "6 AM", "delay": 2},
    {"time": "9 AM", "delay": 28},
    {"time": "12 PM", "delay": 12},
    {"time": "3 PM", "delay": 18},
    {"time": "6 PM", "delay": 35},
    {"time": "9 PM", "delay": 5},
]

# ─── Vehicles (from TrackingPage.jsx) ────────────────────────────────────────

vehicles = {
    "TS09AB4521": {
        "plate": "TS09AB4521",
        "type": "Sedan",
        "color": "White",
        "confidence": "98.7%",
        "status": "ACTIVE",
        "expected": "Kukatpally → Balanagar → Madhapur",
        "actual": "Kukatpally → Begumpet → Madhapur",
        "deviation": "Yes (+3.2 km detour via Begumpet)",
        "stats": ["4", "12.8 km", "24 min", "42 km/h"],
        "reid": "97.8%",
        "transitions": "3",
        "fastest": "48 km/h",
        "slowest": "28 km/h",
        "hops": [
            ["CAM #401", "Kukatpally Y-Junction", "16:02:14", "34 km/h", "98.2%", "North", "0 km", 17.4947, 78.3996],
            ["CAM #402", "Kukatpally Metro Station", "16:07:42", "28 km/h", "99.1%", "North-East", "3.2 km", 17.4985, 78.3912],
            ["CAM #403", "Balanagar Main Road", "16:14:31", "48 km/h", "97.8%", "South", "4.5 km", 17.4682, 78.4357],
            ["CAM #406", "Madhapur IT Corridor", "16:26:05", "42 km/h", "98.7%", "East", "5.1 km", 17.4485, 78.3742],
        ],
    },
    "TS08EJ4892": {
        "plate": "TS08EJ4892",
        "type": "Sedan",
        "color": "Black",
        "confidence": "96.4%",
        "status": "STALE",
        "expected": "Balanagar → Kukatpally",
        "actual": "Balanagar → Kukatpally",
        "deviation": "None (Standard Corridor)",
        "stats": ["3", "8.4 km", "35 min", "36 km/h"],
        "reid": "95.6%",
        "transitions": "2",
        "fastest": "48 km/h",
        "slowest": "28 km/h",
        "hops": [
            ["CAM #403", "Balanagar Main Road Circle", "16:15:20", "48 km/h", "96.4%", "South", "0 km", 17.4682, 78.4357],
            ["CAM #402", "Kukatpally Metro Station", "16:32:45", "28 km/h", "94.2%", "North", "3.8 km", 17.4947, 78.3996],
            ["CAM #401", "Kukatpally Flyover Junction", "16:50:10", "34 km/h", "95.1%", "North-West", "4.6 km", 17.4985, 78.3912],
        ],
    },
    "TS09EE9911": {
        "plate": "TS09EE9911",
        "type": "SUV",
        "color": "White",
        "confidence": "98.1%",
        "status": "ALERT",
        "expected": "Cyberabad → Miyapur",
        "actual": "Cyberabad → JNTU → Miyapur",
        "deviation": "Suspected Evasion Route",
        "stats": ["3", "15.2 km", "70 min", "62 km/h"],
        "reid": "96.9%",
        "transitions": "2",
        "fastest": "70 km/h",
        "slowest": "52 km/h",
        "hops": [
            ["CAM #101", "Cyberabad IT Corridor", "14:10:05", "65 km/h", "98.1%", "West", "0 km", 17.4485, 78.3742],
            ["CAM #105", "JNTU Junction", "14:45:20", "52 km/h", "97.5%", "North", "6.1 km", 17.4925, 78.393],
            ["CAM #112", "Miyapur Metro Station", "15:20:00", "70 km/h", "96.8%", "North-West", "9.1 km", 17.4968, 78.3522],
        ],
    },
    "AP28BY5521": {
        "plate": "AP28BY5521",
        "type": "Sports Coupe",
        "color": "Red",
        "confidence": "99.0%",
        "status": "COMPLETED",
        "expected": "Begumpet → Ameerpet",
        "actual": "Begumpet → Ameerpet",
        "deviation": "None",
        "stats": ["2", "4.5 km", "17 min", "88 km/h"],
        "reid": "98.4%",
        "transitions": "1",
        "fastest": "92 km/h",
        "slowest": "84 km/h",
        "hops": [
            ["CAM #201", "Begumpet Flyover North", "11:05:12", "92 km/h", "99.0%", "South", "0 km", 17.4439, 78.4684],
            ["CAM #204", "Ameerpet Crossroads", "11:22:40", "84 km/h", "97.2%", "West", "4.5 km", 17.4375, 78.4482],
        ],
    },
}

# ─── Traffic Corridors (from TrafficPage.jsx) ────────────────────────────────

traffic_corridors = [
    {
        "id": "COR-01",
        "name": "Kukatpally Y-Junction",
        "status": "Severe",
        "density": 92,
        "speed": 12,
        "trend": "+15%",
        "lat": 17.4947,
        "lng": 78.3996,
        "color": "#ef4444",
        "bottleneck": "Active Signal Jam",
        "length": "1.4 km",
        "duration": "45 mins",
    },
    {
        "id": "COR-02",
        "name": "Cyberabad IT Corridor",
        "status": "High",
        "density": 78,
        "speed": 22,
        "trend": "+5%",
        "lat": 17.4485,
        "lng": 78.3742,
        "color": "#f97316",
        "bottleneck": "Peak Tech Outflow",
        "length": "2.8 km",
        "duration": "30 mins",
    },
    {
        "id": "COR-03",
        "name": "Balanagar Industrial",
        "status": "Moderate",
        "density": 45,
        "speed": 40,
        "trend": "-2%",
        "lat": 17.4682,
        "lng": 78.4357,
        "color": "#eab308",
        "bottleneck": "Heavy Transit Merging",
        "length": "0.9 km",
        "duration": "15 mins",
    },
    {
        "id": "COR-04",
        "name": "JNTU Main Road",
        "status": "Low",
        "density": 25,
        "speed": 55,
        "trend": "Stable",
        "lat": 17.4985,
        "lng": 78.3912,
        "color": "#22c55e",
        "bottleneck": "None",
        "length": "0 km",
        "duration": "0 mins",
    },
]

# ─── O-D Routes (from TrafficPage.jsx) ───────────────────────────────────────

od_routes = [
    {"origin": "Kukatpally", "destination": "Balanagar", "count": "1,842 vehicles"},
    {"origin": "Balanagar", "destination": "Madhapur", "count": "1,426 vehicles"},
    {"origin": "Kukatpally", "destination": "Cyberabad", "count": "2,103 vehicles"},
]

# ─── Alerts (from AlertsPage.jsx) ────────────────────────────────────────────

alerts = [
    {
        "id": "ALT-9041",
        "plateNumber": "TS09EA4512",
        "category": "Blacklisted Vehicle",
        "type": "vehicle",
        "severity": "CRITICAL",
        "timestamp": "Just Now (10:45 PM)",
        "cameraNode": "CAM-04 (Kukatpally Y-Junction)",
        "lat": 17.4947,
        "lng": 78.3996,
        "confidence": "98.4%",
        "description": "National Crime Database match: Stolen SUV reported. Trajectory tracking active.",
        "status": "Active",
    },
    {
        "id": "TRF-3012",
        "plateNumber": "Kukatpally ⇄ JNTU",
        "category": "High-Density Congestion",
        "type": "traffic",
        "severity": "CRITICAL",
        "timestamp": "2 mins ago (10:43 PM)",
        "cameraNode": "CAM-02 (Main Expressway)",
        "lat": 17.4985,
        "lng": 78.3912,
        "confidence": "Sector 2",
        "description": "Severe urban bottleneck: Traffic density exceeded capacity. Average speed dropped to 5 km/h.",
        "status": "Active",
    },
    {
        "id": "TRF-3015",
        "plateNumber": "Cyberabad IT Corridor",
        "category": "Sudden Traffic Surge",
        "type": "traffic",
        "severity": "HIGH",
        "timestamp": "5 mins ago (10:40 PM)",
        "cameraNode": "CAM-07 (Hitec City Flyover)",
        "lat": 17.4485,
        "lng": 78.3742,
        "confidence": "+45% Vol",
        "description": "Unexpected inflow spike. Current count: 1,240 veh/hr (Normal: 850 veh/hr). Signal adjustment advised.",
        "status": "Investigating",
    },
    {
        "id": "ALT-9038",
        "plateNumber": "AP28BK8821",
        "category": "Trajectory Anomaly",
        "type": "vehicle",
        "severity": "HIGH",
        "timestamp": "11 mins ago (10:34 PM)",
        "cameraNode": "CAM-12 (Balanagar Industrial)",
        "lat": 17.4682,
        "lng": 78.4357,
        "confidence": "95.1%",
        "description": "Missing expected camera detection sequence. Vehicle deviated >3km from expected standard route.",
        "status": "Active",
    },
    {
        "id": "ALT-9029",
        "plateNumber": "MH04EF7710",
        "category": "Unusual Stop / Loitering",
        "type": "vehicle",
        "severity": "MEDIUM",
        "timestamp": "24 mins ago (10:21 PM)",
        "cameraNode": "CAM-19 (Begumpet Airport Rd)",
        "lat": 17.4439,
        "lng": 78.4684,
        "confidence": "94.2%",
        "description": "Vehicle stopped for 18 minutes in restricted no-stopping zone. Repeated loitering detected.",
        "status": "Resolved",
    },
]

# ─── Traffic Summary Metrics ─────────────────────────────────────────────────

traffic_metrics = {
    "networkAverageSpeed": "32 km/h",
    "activeBottlenecks": "2 Severe",
    "vehicleVolume1h": "14,280",
    "odRoutesTracked": "1,402",
}
