#!/usr/bin/env python3
"""
TraceNet — prepare the simulated CCTV network for the MediaMTX restreamer.

    python backend/scripts/prepare_streams.py            # transcode feeds + write docker/mediamtx.yml
    docker compose up -d mediamtx                        # RTSP :8554 · HLS :8888 · WebRTC :8889

Each camera's recorded footage (public/camera-feeds/CAM-*.mp4, plus any synthetic dataset clips in
backend/output/dataset/videos/) is transcoded ONCE to a stream-friendly file in backend/output/streams/:
native resolution (ANPR needs every plate pixel - a 720p downscale leaves plates too small to read),
H.264 high, 25 fps, 1 s GOP (keyframe every second, so low-latency HLS segments line up), no audio.
MediaMTX then loops each file into rtsp://localhost:8554/<CAM> with `-c copy` (no ongoing transcode),
exactly like a live camera: ingestion reads it over RTSP, the React Cameras page plays it over HLS.

The recorded footage is the simulation layer for the unavailable city cameras; the stream is labelled
as a restream of that footage in the API (/api/v1/streams) and in the UI.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
FEEDS_DIR = PROJECT_ROOT / "public" / "camera-feeds"
DATASET_VIDEOS = PROJECT_ROOT / "backend" / "output" / "dataset" / "videos"
STREAMS_DIR = PROJECT_ROOT / "backend" / "output" / "streams"
MEDIAMTX_CONFIG = PROJECT_ROOT / "docker" / "mediamtx.yml"

CONFIG_HEADER = """\
# TraceNet — MediaMTX restreamer config. GENERATED by backend/scripts/prepare_streams.py; edit that script.
#
#   rtsp://localhost:8554/<CAM>                   ingestion (TRACENET_INGEST_SOURCE=rtsp)
#   http://localhost:8888/<CAM>/index.m3u8        low-latency HLS for the React Cameras page
#   http://localhost:8889/<CAM>                   WebRTC (WHEP) player
#
# Every path loops a pre-transcoded file from backend/output/streams (mounted at /streams) with
# `ffmpeg -c copy`, restarted automatically if it exits - an always-on simulated CCTV camera.

logLevel: warn
rtmp: no
srt: no
hlsAlwaysRemux: yes          # keep every muxer warm: the first viewer gets video immediately
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
webrtcAdditionalHosts: [127.0.0.1]

paths:
"""

PATH_TEMPLATE = """\
  {cam}:
    runOnInit: ffmpeg -hide_banner -loglevel error -re -stream_loop -1 -i /streams/{cam}.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:$RTSP_PORT/$MTX_PATH
    runOnInitRestart: yes
"""


def ffmpeg_exe() -> str:
    try:
        import imageio_ffmpeg

        return imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return "ffmpeg"


def source_clips() -> dict[str, Path]:
    clips: dict[str, Path] = {}
    for folder in (FEEDS_DIR, DATASET_VIDEOS):     # dataset clips never override real footage
        if not folder.exists():
            continue
        for f in sorted(folder.glob("CAM-*.mp4")):
            cam = f.stem.split("_")[0]
            if "_" in f.stem or cam in clips:     # skip *_annotated.mp4 etc.
                continue
            clips[cam] = f
    return clips


def transcode(src: Path, dst: Path, force: bool = False) -> bool:
    if dst.exists() and not force and dst.stat().st_mtime >= src.stat().st_mtime:
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    tmp = dst.with_suffix(".tmp.mp4")
    cmd = [ffmpeg_exe(), "-hide_banner", "-loglevel", "error", "-y", "-i", str(src),
           "-an", "-vf", "fps=25",
           "-c:v", "libx264", "-profile:v", "high", "-preset", "veryfast", "-crf", "21", "-pix_fmt", "yuv420p",
           "-g", "25", "-keyint_min", "25", "-sc_threshold", "0", "-bf", "0",
           "-movflags", "+faststart", str(tmp)]
    subprocess.run(cmd, check=True)
    try:
        tmp.replace(dst)
    except PermissionError:                     # Windows: the running restreamer holds the old file open
        tmp.unlink(missing_ok=True)
        raise SystemExit(f"[ERROR] {dst.name} is in use - run `docker compose stop mediamtx`, then retry")
    return True


def write_config(cameras: list[str]) -> None:
    MEDIAMTX_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    body = CONFIG_HEADER + "".join(PATH_TEMPLATE.format(cam=c) for c in cameras)
    MEDIAMTX_CONFIG.write_text(body, encoding="utf-8", newline="\n")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--force", action="store_true", help="re-transcode even when up to date")
    args = p.parse_args(argv)
    clips = source_clips()
    if not clips:
        print(f"[ERROR] no camera clips in {FEEDS_DIR} or {DATASET_VIDEOS}", file=sys.stderr)
        return 1
    for cam, src in clips.items():
        dst = STREAMS_DIR / f"{cam}.mp4"
        done = transcode(src, dst, args.force)
        print(f"  {cam}: {src.relative_to(PROJECT_ROOT)} -> {dst.relative_to(PROJECT_ROOT)}"
              f" ({'transcoded' if done else 'up to date'}, {dst.stat().st_size / 1e6:.1f} MB)")
    write_config(sorted(clips))
    manifest = {cam: {"origin": "synthetic dataset clip (generate_dataset.py)" if DATASET_VIDEOS in src.parents
                      else "recorded camera footage", "source": str(src.relative_to(PROJECT_ROOT)).replace("\\", "/")}
                for cam, src in clips.items()}
    (STREAMS_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"  config: {MEDIAMTX_CONFIG.relative_to(PROJECT_ROOT)} ({len(clips)} streams)")
    print("  next:   docker compose up -d mediamtx   (it reloads the config automatically)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
