import { useEffect, useState } from "react";
import { CheckCircle2, Scan } from "lucide-react";
import { formatConfidence } from "../demoData";

export default function OCRPanel({ ocrData, isActive }) {
  const [revealed, setRevealed] = useState(false);
  useEffect(() => { if (!isActive) { setRevealed(false); return undefined; } const timer = window.setTimeout(() => setRevealed(true), 1200); return () => window.clearTimeout(timer); }, [isActive]);
  if (!isActive || !ocrData) return null;
  return <section className="glass-card-static mt-4 p-5"><div className="mb-4 flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-widest text-[var(--text-muted)]"><Scan size={14} className="text-blue-400" /> OCR evidence / multi-frame consensus</div><div className="grid grid-cols-3 gap-2">{ocrData.candidateFrames.slice(0, 3).map((frame, index) => <div key={index} className={`rounded-xl border bg-[#080d19] p-2 transition-all duration-500 ${revealed && frame.selected ? "border-blue-400/60 shadow-[0_0_14px_rgba(59,130,246,.18)]" : "border-white/[0.08] opacity-60"}`}><div className="mb-2 rounded-md border border-white/[0.07] bg-white/[0.04] py-2 text-center font-mono text-[10px] tracking-widest text-[var(--text-primary)]">{frame.ocrOutput}</div><div className="flex justify-between text-[8px] text-[var(--text-muted)]"><span>{frame.camera}</span><span className={revealed && frame.selected ? "font-bold text-blue-400" : ""}>{formatConfidence(frame.ocrConfidence)}</span></div></div>)}</div><div className={`mt-4 flex items-center justify-between overflow-hidden rounded-xl border border-emerald-500/20 bg-emerald-500/[0.06] p-3 transition-all duration-500 ${revealed ? "max-h-24 opacity-100" : "max-h-0 border-0 p-0 opacity-0"}`}><div className="flex items-center gap-2"><CheckCircle2 size={16} className="text-emerald-400" /><div><p className="text-[9px] font-extrabold uppercase tracking-wider text-emerald-400">Final validation</p><p className="font-mono text-sm font-black text-[var(--text-primary)]">{ocrData.consensusPlate}</p></div></div><strong className="text-lg text-emerald-400">{formatConfidence(ocrData.consensusConfidence)}</strong></div></section>;
}
