import { useEffect, useState } from "react";
import { Fingerprint, ShieldCheck } from "lucide-react";
import { formatConfidence } from "../demoData";

export default function ReIDPanel({ matchData, fromCamera, toCamera, globalId, isActive }) {
  const [progress, setProgress] = useState({ plate: 0, appearance: 0, type: 0, color: 0, time: 0, route: 0 });
  const [confirmed, setConfirmed] = useState(false);
  useEffect(() => { if (!isActive || !matchData) { setProgress({ plate: 0, appearance: 0, type: 0, color: 0, time: 0, route: 0 }); setConfirmed(false); return undefined; } const keys = [["plate", "plateSimilarity"], ["appearance", "appearanceSimilarity"], ["type", "vehicleTypeMatch"], ["color", "vehicleColorMatch"], ["time", "timeFeasibility"], ["route", "routeFeasibility"]]; const timers = keys.map(([key, source], i) => window.setTimeout(() => setProgress((state) => ({ ...state, [key]: matchData[source] })), 300 + i * 180)); timers.push(window.setTimeout(() => setConfirmed(true), 1650)); return () => timers.forEach(window.clearTimeout); }, [isActive, matchData]);
  if (!isActive || !matchData) return null;
  const metric = (label, value) => <div><div className="mb-1 flex justify-between text-[9px] font-bold uppercase tracking-wider text-[var(--text-muted)]"><span>{label}</span><span>{value ? formatConfidence(value) : "—"}</span></div><div className="h-1 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-400 transition-all duration-700" style={{ width: `${value}%` }} /></div></div>;
  return <section className="glass-card-static mt-4 p-5"><div className="mb-4 flex items-center justify-between"><span className="flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-widest text-[var(--text-muted)]"><Fingerprint size={14} className="text-blue-400" /> Re-identification</span>{confirmed ? <span className="badge badge-emerald"><ShieldCheck size={12} /> Confirmed</span> : <span className="badge badge-amber">Matching</span>}</div><p className="mb-4 text-center font-mono text-[10px] font-bold text-[var(--text-secondary)]">{fromCamera} <span className="mx-2 text-blue-400">→</span> {toCamera}</p><div className="space-y-3">{metric("Plate similarity", progress.plate)}{metric("Visual appearance", progress.appearance)}{metric("Vehicle type", progress.type)}{metric("Colour match", progress.color)}{metric("Time feasibility", progress.time)}{metric("Route feasibility", progress.route)}</div><div className={`mt-4 rounded-xl border p-3 text-center ${confirmed ? "border-blue-500/25 bg-blue-500/[0.06]" : "border-[var(--border-subtle)] bg-white/[0.02] opacity-60"}`}><span className="text-[9px] font-extrabold uppercase tracking-widest text-[var(--text-muted)]">Overall match</span><p className="mt-1 text-xl font-black text-blue-400">{confirmed ? formatConfidence(matchData.overallConfidence) : "…"}</p><span className="font-mono text-[10px] font-bold text-[var(--text-muted)]">Global ID: {globalId}</span></div></section>;
}
