export const slides = [
  {
    title: "Trace Net Intelligence Core",
    desc: "Modern cities operate on isolated camera feeds. Trace Net integrates cross-sector infrastructure using centralized computer vision and deep learning to deliver real-time traffic visibility, trajectory reconstruction, and congestion analytics.",
  },
  {
    title: "High-Accuracy ANPR & OCR Engine",
    desc: "Optical Recognition Core: Advanced deep learning architecture achieving >96.8% precision across harsh environmental conditions, high-speed motion blur, angled multi-lane shots, and faded or damaged license plates.",
  },
  {
    title: "Macro Traffic Flow & Origin Analytics",
    desc: "City Dynamics: Aggregates over 250+ live feeds to continuously map corridor density, compute origin-destination matrices, forecast bottlenecks 30 minutes in advance, and optimize traffic signal timing dynamically.",
  },
  {
    title: "Autonomous Threat & Incident Response",
    desc: "Security Layer: Instantly flags blacklisted vehicles, anomalous loitering patterns, and erratic lane-changing behaviors with automated dispatch alerts routed directly to local command posts.",
  },
];

export const areas = [
  {
    name: "Kukatpally",
    title: "Kukatpally Zone",
    sector: "Sector NW-1",
    density: "High (Congestion Detected)",
    speed: "36 km/h",
    cameras: "54 ANPR Cameras",
    accuracy: "95.1%",
    status: "Critical Load",
    peakHours: "17:30 - 20:00",
    incidents: 4,
    color: "#ff3b30",
    position: [17.4932, 78.3984],
  },
  {
    name: "Balanagar",
    title: "Balanagar Corridor",
    sector: "Sector N-2",
    density: "Moderate",
    speed: "48 km/h",
    cameras: "38 ANPR Cameras",
    accuracy: "93.7%",
    status: "Stable Flow",
    peakHours: "08:30 - 10:30",
    incidents: 1,
    color: "#ffcc00",
    position: [17.5180, 78.4275],
  },
  {
    name: "Cyberabad / Madhapur",
    title: "Cyberabad Hub (Madhapur)",
    sector: "Sector W-4",
    density: "Very High Flow",
    speed: "42 km/h",
    cameras: "72 ANPR Cameras",
    accuracy: "96.4%",
    status: "Heavy Commuter Surge",
    peakHours: "16:00 - 21:00",
    incidents: 7,
    color: "#007aff",
    position: [17.4483, 78.3915],
  },
  {
    name: "Begumpet",
    title: "Begumpet Central",
    sector: "Sector C-1",
    density: "Moderate Density",
    speed: "40 km/h",
    cameras: "41 ANPR Cameras",
    accuracy: "94.2%",
    status: "Normal Operations",
    peakHours: "09:00 - 11:00",
    incidents: 2,
    color: "#ffcc00",
    position: [17.4440, 78.4670],
  },
  {
    name: "Secunderabad",
    title: "Secunderabad Hub",
    sector: "Sector E-3",
    density: "Normal Flow",
    speed: "55 km/h",
    cameras: "49 ANPR Cameras",
    accuracy: "92.8%",
    status: "Optimal Flow",
    peakHours: "08:00 - 10:00",
    incidents: 0,
    color: "#34c759",
    position: [17.4399, 78.4983],
  },
];

export const cameras = [
  {
    id: "CAM #401",
    location: "Kukatpally Flyover Junction",
    latitude: 17.4932,
    longitude: 78.3984,
    speed: "34 km/h",
    density: "High (84%)",
    trend: "Traffic ↑ 18% since 4:00 PM",
    status: "Online",
    resolution: "4K AI Optical Stream",
    fps: 60,
    color: "#e64638",
    flow: [0.4, 0.7, 1.0, 0.8, 0.5, 0.9],
    vehicleClasses: { cars: "62%", bikes: "24%", trucks: "14%" },
    lastPlateRead: "TS08EJ4892",
    videoFeed: "/camera-feeds/CAM-401.mp4",
  },
  {
    id: "CAM #402",
    location: "Kukatpally Metro Station Gate 2",
    latitude: 17.4891,
    longitude: 78.4012,
    speed: "28 km/h",
    density: "Very High (92%)",
    trend: "Traffic ↑ 24% since 3:30 PM",
    status: "Online",
    resolution: "1080p IR Night-Enhanced",
    fps: 30,
    color: "#e64638",
    flow: [0.5, 0.9, 1.15, 0.85, 0.6, 1.1],
    vehicleClasses: { cars: "55%", bikes: "35%", trucks: "10%" },
    lastPlateRead: "TS07FZ1029",
    videoFeed: "/camera-feeds/CAM-402.mp4",
  },
  {
    id: "CAM #403",
    location: "Balanagar Main Road Circle",
    latitude: 17.4855,
    longitude: 78.4120,
    speed: "48 km/h",
    density: "Medium (56%)",
    trend: "Traffic ↑ 4% since 4:00 PM",
    status: "Online",
    resolution: "4K Wide Angle Matrix",
    fps: 60,
    color: "#f4be25",
    flow: [0.3, 0.5, 0.7, 0.6, 0.4, 0.5],
    vehicleClasses: { cars: "48%", bikes: "30%", trucks: "22%" },
    lastPlateRead: "TS10UA9921",
    videoFeed: "/camera-feeds/CAM-403.mp4",
  },
  {
    id: "CAM #404",
    location: "Moosapet Bypass Link",
    latitude: 17.4810,
    longitude: 78.4055,
    speed: "56 km/h",
    density: "Low (32%)",
    trend: "Traffic ↓ 6% since 4:00 PM",
    status: "Online",
    resolution: "1080p Standard Telephoto",
    fps: 30,
    color: "#52b788",
    flow: [0.2, 0.4, 0.5, 0.3, 0.3, 0.25],
    vehicleClasses: { cars: "70%", bikes: "20%", trucks: "10%" },
    lastPlateRead: "TS15EX5540",
    videoFeed: "/camera-feeds/CAM-401.mp4",
  },
];

export const systemMetrics = {
  totalNodesActive: 254,
  networkUptime: "99.98%",
  averageInferenceLatency: "14ms",
  platesIndexedToday: "1,428,910",
  activeAlertsCount: 3,
};